INFO - 2025-06-30 01:22:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-30 01:22:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-06-30 01:24:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-06-30 01:24:20 --> mysqli_sql_exception: Table 'veterinaria_db.usuarios' doesn't exist in C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\Model.php(271): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\BaseModel.php(679): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\veterinaria_qr\app\Controllers\Login.php(29): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Login->authenticate()
#8 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\veterinaria_qr\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\veterinaria_qr\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2025-06-30 01:24:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'veterinaria_db.usuarios' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(271): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(679): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Login.php(29): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Login->authenticate()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-06-30 01:24:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'veterinaria_db.usuarios' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuarios`
WHERE `email` = \'ed@gmail.com\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuarios`
WHERE `email` = \'ed@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(271): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(679): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\Login.php(29): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Login->authenticate()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-06-30 01:24:20 --> [Caused by] mysqli_sql_exception: Table 'veterinaria_db.usuarios' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `usuarios`
WHERE `email` = \'ed@gmail.com\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuarios`
WHERE `email` = \'ed@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuarios`
WHERE `email` = \'ed@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(271): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(679): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\Login.php(29): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Login->authenticate()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
